[package]
name = "Wannacut"
version = "0.3.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "Wannacut_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-opener = "2"
tauri-plugin-dialog = "2.6.0"
tauri-plugin-fs = "2"
tauri-plugin-shell = "2"
tauri-plugin-localhost = "2.0.0" # Verifique a versão compatível com seu Tauri
percent-encoding = "2.3"
tiny_http = "0.12"
tokio = { version = "1", features = ["full"] }
image = "0.24"
fs_extra = "1.3.0"
tauri-plugin-notification = "2"
sha2 = "0.10"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", features = ["json", "blocking"] }
ed25519-dalek = { version = "2", features = ["serde"] }
base64 = "0.22"
dirs = "5"
machine-uid = "0.5"
chrono = { version = "0.4", features = ["serde"] }
thiserror = "2"

